"""
Django settings for Medicine_Portal project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os, sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@gbfq)cl3&ediq=1vn4&34(ocy4v1*72j_o10ok2h7f=@fxhg7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
DOMAIN = "http://18.216.201.143"

ALLOWED_HOSTS = ['*']
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# SITE_PATH = os.path.abspath(os.path.dirname(__file__))
# PROJECT_PATH = os.path.normpath(os.path.join(SITE_PATH, '..', '..'))
# SRC_PATH = os.path.join(PROJECT_PATH, 'libraries')
# if SRC_PATH not in sys.path:
#     sys.path.insert(0, SRC_PATH)


# Application definition

INSTALLED_APPS = [
    'jet.dashboard',
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'medicine_app',
    'django_extensions',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_generators',   
]
#pip install psycopg2-binary

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # <-- And here
    ],
}


JET_SIDE_MENU_COMPACT = True
X_FRAME_OPTIONS = 'SAMEORIGIN'
JET_DEFAULT_THEME = 'light-gray'



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Medicine_Portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Medicine_Portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


#NOTE:#https://www.shubhamdipt.com/blog/django-transfer-data-from-sqlite-to-another-database/
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql', 
#         'NAME': 'dev',
#         'USER': 'root',
#         'PASSWORD': 'root1234',
#         'HOST': '18.216.201.143',   # Or an IP Address that your DB is hosted on
#         'PORT': '3306',
#     }
# }

import platform
if platform.uname()[1] == "DESKTOP-X3CY1ON":
    DATABASES = {

        'default': {

            'ENGINE': 'django.db.backends.postgresql_psycopg2',

            'NAME': 'dev',

            'USER': 'postgres',

            'PASSWORD': 'root1234',

            'HOST': '18.216.201.143',

            'PORT': '5432',

        }

    }
else:
    DATABASES = {

        'default': {

            'ENGINE': 'django.db.backends.postgresql_psycopg2',

            'NAME': 'dev',

            'USER': 'postgres',

            'PASSWORD': 'root1234',

            'HOST': 'localhost',

            'PORT': '5432',

        }

    }

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

BASE_DIR = os.path.dirname(os.path.dirname(__file__))
if DEBUG:
    STATIC_URL = '/static/'
    #STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static')
   ]

    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'static/media/')
else:
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'
    #STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
    MEDIA_ROOT = os.path.join(BASE_DIR, 'static/media/')
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static')
    ]

LOGIN_URL = "/login"