# Generated by Django 3.0.8 on 2020-07-30 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import medicine_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin_B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, max_length=60, null=True)),
                ('address', models.TextField(default='P.O. Box 99376 - 80100, Mombasa. P.O. Box 2138 - 20100, Nakuru.', max_length=350, null=True)),
                ('phone', models.TextField(default='+ 254 (20) 694 8000', max_length=60, null=True)),
                ('email', models.TextField(default='info@kebs.org', max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin_C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, max_length=60, null=True)),
                ('address', models.TextField(default=None, max_length=350, null=True)),
                ('phone', models.TextField(default=None, max_length=60, null=True)),
                ('email', models.TextField(default=None, max_length=60, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Boxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, default=medicine_app.models.code_generation, max_length=100)),
                ('quantity', models.IntegerField()),
                ('importer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Admin_B')),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField(null=True)),
                ('chemical', models.CharField(default=None, max_length=200)),
                ('generic', models.CharField(default=None, max_length=200)),
                ('profile', models.CharField(default='drugs', max_length=50)),
                ('item_type', models.TextField(choices=[('TABLETS', 'TABLETS'), ('GEL', 'GEL'), ('INJECTION', 'INJECTION'), ('CAPSULES', 'CAPSULES'), ('SYRUP', 'SYRUP'), ('SUSPENSION', 'SUSPENSION')], default=None, max_length=50, null=True)),
                ('measure', models.TextField(choices=[('TABLETS', 'TABLETS'), ('PIECE', 'PIECE'), ('TUBE', 'TUBE'), ('VIALS', 'VIALS'), ('AMPOULES', 'AMPOULES'), ('BOTTLE', 'BOTTLE')], default=None, max_length=50, null=True)),
                ('formulation', models.TextField(choices=[('TABLETS', 'TABLETS'), ('CREAM', 'CREAM'), ('INJECTION', 'INJECTION'), ('SUSPENSION', 'SUSPENSION'), ('SYRUP', 'SYRUP'), ('ORAL SOLUTION', 'ORAL SOLUTION')], default=None, max_length=50, null=True)),
                ('route', models.TextField(choices=[('PO', 'PO'), ('IV', 'IV'), ('PR', 'PR'), ('IM', 'IM'), ('TOPICAL', 'TOPICAL')], default=None, max_length=50, null=True)),
                ('pbb_code', models.CharField(default=None, max_length=50, null=True)),
                ('importer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Admin_B')),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=60)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('admin_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_a', to='medicine_app.Admin_A')),
                ('admin_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_b', to='medicine_app.Admin_B')),
                ('admin_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_c', to='medicine_app.Admin_C')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Medicines')),
                ('super_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superadmin', to='medicine_app.SuperAdmin')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('code', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_box', models.BooleanField(default=False)),
                ('box', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Boxes')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Medicines')),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exported_file', models.FileField(blank=True, default=None, upload_to='')),
                ('printed_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='boxes',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Medicines'),
        ),
    ]
