# Generated by Django 3.0.6 on 2020-06-30 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical', models.TextField(default=None, max_length=200)),
                ('generic', models.TextField(default=None, max_length=200)),
                ('amount', models.TextField(default=None, max_length=200)),
                ('profile', models.TextField(default='drugs', max_length=50)),
                ('item_type', models.TextField(choices=[('TABLETS', 'TABLETS'), ('GEL', 'GEL'), ('INJECTION', 'INJECTION'), ('CAPSULES', 'CAPSULES'), ('SYRUP', 'SYRUP'), ('SUSPENSION', 'SUSPENSION')], default=None, max_length=50, null=True)),
                ('measure', models.TextField(choices=[('TABLETS', 'TABLETS'), ('PIECE', 'PIECE'), ('TUBE', 'TUBE'), ('VIALS', 'VIALS'), ('AMPOULES', 'AMPOULES'), ('BOTTLE', 'BOTTLE')], default=None, max_length=50, null=True)),
                ('formulation', models.TextField(choices=[('TABLETS', 'TABLETS'), ('CREAM', 'CREAM'), ('INJECTION', 'INJECTION'), ('SUSPENSION', 'SUSPENSION'), ('SYRUP', 'SYRUP'), ('ORAL SOLUTION', 'ORAL SOLUTION')], default=None, max_length=50, null=True)),
                ('route', models.TextField(choices=[('PO', 'PO'), ('IV', 'IV'), ('PR', 'PR'), ('IM', 'IM'), ('TOPICAL', 'TOPICAL')], default=None, max_length=50, null=True)),
                ('pbb_code', models.TextField(default=None, max_length=50, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Brands')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=60)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('admin_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_a', to='medicine_app.Admin_A')),
                ('admin_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_b', to='medicine_app.Admin_B')),
                ('admin_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_c', to='medicine_app.Admin_C')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Medicines')),
                ('super_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superadmin', to='medicine_app.SuperAdmin')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=100)),
                ('box', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Boxes')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Medicines')),
            ],
        ),
        migrations.AddField(
            model_name='boxes',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Medicines'),
        ),
    ]
