# Generated by Django 3.0.6 on 2020-06-22 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0002_boxes_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='box',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Boxes'),
        ),
    ]
