# Generated by Django 3.0.8 on 2020-07-30 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0002_boxes_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxes',
            name='target',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Admin_C'),
        ),
    ]
