# Generated by Django 3.0.6 on 2020-06-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0002_auto_20200630_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicines',
            name='amount',
        ),
        migrations.AlterField(
            model_name='medicines',
            name='chemical',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='generic',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='pbb_code',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
