# Generated by Django 3.0.8 on 2020-08-02 22:32

import datetime
from django.db import migrations, models
import medicine_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0003_boxes_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='batch_no',
            field=models.CharField(default=medicine_app.models.random_num, max_length=50),
        ),
        migrations.AddField(
            model_name='medicines',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='medicines',
            name='manufacturer_name',
            field=models.CharField(default='Manufacturer INC.', max_length=55),
        ),
        migrations.AddField(
            model_name='medicines',
            name='manufacturing_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
