# Generated by Django 3.0.6 on 2020-06-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0003_auto_20200630_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='profile',
            field=models.CharField(default='drugs', max_length=50),
        ),
    ]
