# Generated by Django 3.0.6 on 2020-06-30 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0004_auto_20200630_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.SubCategories'),
        ),
    ]
