# Generated by Django 3.0.8 on 2020-08-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0004_auto_20200803_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='manufactturer_address',
            field=models.CharField(default='Meldi Estate, Near Prasang Party Plot,  \nOpp. Sola Bhagwat, Sayona City Road,  \nGota, Ahmedabad - 382481  \nGujarat, India', max_length=500),
        ),
    ]
