# Generated by Django 3.0.8 on 2020-08-06 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0005_medicines_manufactturer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Admin_C'),
        ),
    ]
