# Generated by Django 3.0.6 on 2020-06-30 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0006_auto_20200630_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicines',
            name='category',
        ),
    ]
