# Generated by Django 3.0.8 on 2020-08-09 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import medicine_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine_app', '0006_auto_20200806_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, upload_to=medicine_app.models.file_upload)),
            ],
        ),
        migrations.AddField(
            model_name='boxes',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PBB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Pharmacy & Poisons Board', max_length=60, null=True)),
                ('address', models.TextField(default='P.O. Box 27663 – 00506, Nairobi. Lenana Road Opp. DOD', max_length=350, null=True)),
                ('phone', models.TextField(default='+254 709 770 100', max_length=60, null=True)),
                ('email', models.TextField(default='info@pharmacyboardkenya.org', max_length=60, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
