# Generated by Django 3.0.8 on 2020-07-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0008_medicines_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='is_box',
            field=models.BooleanField(default=None),
        ),
    ]
