# Generated by Django 3.0.8 on 2020-08-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0008_auto_20200809_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_b',
            name='user',
        ),
    ]
