# Generated by Django 3.0.8 on 2020-07-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0009_items_is_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='is_box',
            field=models.BooleanField(default=False),
        ),
    ]
