# Generated by Django 3.0.8 on 2020-08-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0010_auto_20200809_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_b',
            name='user',
        ),
    ]
