# Generated by Django 3.0.8 on 2020-07-20 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0010_auto_20200720_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='importer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Admin_B'),
        ),
    ]
