# Generated by Django 3.0.8 on 2020-07-20 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine_app', '0011_items_importer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='importer',
        ),
        migrations.AddField(
            model_name='boxes',
            name='importer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Admin_B'),
        ),
        migrations.AddField(
            model_name='items',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
