# Generated by Django 3.0.8 on 2020-08-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0011_remove_admin_b_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_b',
            name='user_type',
        ),
    ]
