# Generated by Django 3.0.8 on 2020-08-09 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine_app', '0012_remove_admin_b_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='box',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Boxes'),
        ),
        migrations.AlterField(
            model_name='items',
            name='medicine',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Medicines'),
        ),
        migrations.AlterField(
            model_name='items',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
