# Generated by Django 3.0.8 on 2020-07-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0013_auto_20200720_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_b',
            name='address',
            field=models.TextField(default=None, max_length=350),
        ),
        migrations.AddField(
            model_name='admin_b',
            name='email',
            field=models.TextField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='admin_b',
            name='name',
            field=models.TextField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='admin_b',
            name='phone',
            field=models.TextField(default=None, max_length=60),
        ),
    ]
