# Generated by Django 3.0.8 on 2020-08-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0013_auto_20200809_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCodeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=100000000000)),
            ],
        ),
    ]
