# Generated by Django 3.0.8 on 2020-08-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0014_systemcodecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcodecount',
            name='count',
            field=models.TextField(default='100000000000'),
        ),
    ]
