# Generated by Django 3.0.8 on 2020-07-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0014_auto_20200720_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_b',
            name='address',
            field=models.TextField(default=None, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='admin_b',
            name='email',
            field=models.TextField(default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='admin_b',
            name='name',
            field=models.TextField(default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='admin_b',
            name='phone',
            field=models.TextField(default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='admin_c',
            name='address',
            field=models.TextField(default=None, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='admin_c',
            name='email',
            field=models.TextField(default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='admin_c',
            name='name',
            field=models.TextField(default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='admin_c',
            name='phone',
            field=models.TextField(default=None, max_length=60, null=True),
        ),
    ]
