# Generated by Django 3.0.8 on 2020-07-20 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0015_auto_20200720_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_b',
            name='address',
        ),
        migrations.RemoveField(
            model_name='admin_c',
            name='address',
        ),
    ]
