# Generated by Django 3.0.8 on 2020-08-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0015_auto_20200809_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcodecount',
            name='download',
            field=models.TextField(default='100000000000'),
        ),
    ]
