# Generated by Django 3.0.8 on 2020-07-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0016_auto_20200720_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_b',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admin_b',
            name='name',
        ),
        migrations.RemoveField(
            model_name='admin_b',
            name='phone',
        ),
    ]
