# Generated by Django 3.0.8 on 2020-08-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0016_systemcodecount_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
