# Generated by Django 3.0.8 on 2020-08-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0017_items_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='first_column',
            field=models.TextField(default=None, max_length=15, null=True),
        ),
    ]
