# Generated by Django 3.0.8 on 2020-08-10 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine_app', '0018_items_first_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Medcure Healthcare Ltd', max_length=60, null=True)),
                ('address', models.TextField(default='P.O. Box 14608-00400 Nairobi, Kenya', max_length=350, null=True)),
                ('phone', models.TextField(default='+254 (0)20 356 9904 ', max_length=60, null=True)),
                ('email', models.TextField(default='info@medcurehealthcare.com', max_length=60, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Medcure Healthcare Ltd', max_length=60, null=True)),
                ('address', models.TextField(default='P.O. Box 14608-00400 Nairobi, Kenya', max_length=350, null=True)),
                ('phone', models.TextField(default='+254 (0)20 356 9904 ', max_length=60, null=True)),
                ('email', models.TextField(default='info@medcurehealthcare.com', max_length=60, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Manufacturer',
            new_name='Distributors',
        ),
        migrations.RenameModel(
            old_name='Admin_C',
            new_name='Pharmacies',
        ),
        migrations.RemoveField(
            model_name='boxes',
            name='target',
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
        migrations.AlterField(
            model_name='boxes',
            name='importer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Importers'),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='importer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Importers'),
        ),
        migrations.DeleteModel(
            name='Admin_B',
        ),
    ]
