# Generated by Django 3.0.8 on 2020-08-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0019_auto_20200810_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicines',
            name='manufactturer_address',
        ),
        migrations.RemoveField(
            model_name='medicines',
            name='manufacturer_name',
        ),
        migrations.AddField(
            model_name='medicines',
            name='manufacturer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Manufacturers'),
        ),
    ]
