# Generated by Django 3.0.8 on 2020-07-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0019_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='id',
        ),
        migrations.AlterField(
            model_name='items',
            name='code',
            field=models.TextField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
