# Generated by Django 3.0.8 on 2020-07-23 10:40

from django.db import migrations, models
import medicine_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0020_auto_20200722_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxes',
            name='code',
            field=models.TextField(blank=True, default=medicine_app.models.code_generation, max_length=100),
        ),
    ]
