# Generated by Django 3.0.8 on 2020-08-10 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine_app', '0020_auto_20200810_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Medcure Healthcare Ltd', max_length=60, null=True)),
                ('address', models.TextField(default='P.O. Box 14608-00400 Nairobi, Kenya', max_length=350, null=True)),
                ('phone', models.TextField(default='+254 (0)20 356 9904 ', max_length=60, null=True)),
                ('email', models.TextField(default='info@medcurehealthcare.com', max_length=60, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
