# Generated by Django 3.0.8 on 2020-08-10 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0021_chemists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='owner',
        ),
        migrations.AddField(
            model_name='items',
            name='importer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Importers'),
        ),
        migrations.AddField(
            model_name='items',
            name='manufacturer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Manufacturers'),
        ),
    ]
