# Generated by Django 3.0.8 on 2020-07-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0021_auto_20200723_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicines',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='medicines',
            name='category',
        ),
        migrations.AddField(
            model_name='medicines',
            name='importer',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='medicines',
            name='item_no',
            field=models.IntegerField(null=True),
        ),
    ]
