# Generated by Django 3.0.8 on 2020-08-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0022_auto_20200810_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='is_issued',
            field=models.BooleanField(default=False),
        ),
    ]
