# Generated by Django 3.0.8 on 2020-07-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0022_auto_20200723_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_b',
            name='user',
        ),
        migrations.AlterField(
            model_name='admin_b',
            name='address',
            field=models.TextField(default='P.O. Box 99376 - 80100, Mombasa. P.O. Box 2138 - 20100, Nakuru.', max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='admin_b',
            name='email',
            field=models.TextField(default='info@kebs.org', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='admin_b',
            name='phone',
            field=models.TextField(default='+ 254 (20) 694 8000', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='importer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Admin_B'),
        ),
    ]
