# Generated by Django 3.0.8 on 2020-08-14 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0023_items_is_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='distributor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Distributors'),
        ),
    ]
