# Generated by Django 3.0.8 on 2020-08-14 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0024_medicines_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='distributor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Distributors'),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='importer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Importers'),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='manufacturer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Manufacturers'),
        ),
    ]
