# Generated by Django 3.0.8 on 2020-08-14 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0025_auto_20200814_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='distributor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Distributors'),
        ),
    ]
