# Generated by Django 3.0.8 on 2020-08-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0026_items_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
